server:
   port: 9092
spring:
  application:
    name: greet-api
  boot:
   admin:
     client:
      url: http://loclhost:1111/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
